- hosts: master
  become: yes
  vars:
    aws_account: 318180760014
    aws_output_format: 'json'
    aws_region: 'us-west-2'
    aws_access_key_id: 'my_access_key'
    aws_secret_access_key: 'my_secret_key'
  tasks:  
    - name: 'Create the AWS config directory'
      tags: 'aws-cli'
      become_user: ubuntu
      file: >
        path=~/.aws
        state=directory
        mode=0755

    - name: 'Copy AWS CLI config'
      tags: 'aws-cli'
      become_user: ubuntu
      template: >
        src=aws_cli_config.j2
        dest=~/.aws/config
        mode=0600

    - name: 'Copy AWS CLI credentials'
      tags: 'aws-cli'
      become_user: ubuntu
      template: >
        src=aws_cli_credentials.j2
        dest=~/.aws/credentials
        mode=0600

    - name: 'Add script for kubernetes ecr secrets'
      tags: 'aws-cli'
      become_user: ubuntu
      template: >
        src=aws_update_credentials.j2
        dest=~/.aws/aws_update_credentials.sh
        mode=0755

    - name: Create kubernetes ecr secret
      become_user: ubuntu
      shell: "~/.aws/aws_update_credentials.sh"

    - name: Ensure aws ecr secret is reloaded every 6 hours
      become_user: ubuntu
      cron:
        name: "AWS login"
        minute: "0"
        hour: "*/6"
        job: "~/.aws/aws_update_credentials.sh"