version: '3.1'
services:
  fibonacci:
    build: .
    container_name: fibonacci 
    environment: 
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    logging:
      driver: "json-file"
    volumes:
      - .:/app
