pipeline {
    agent any
    stages {
        stage('first') {
            steps {
                sh 'echo "Changing app dir"'
                sh '''
                    cd app
                    ls -lah
                '''
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Building docker image"'
                sh 'make build'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "Testing image"'
                sh 'make test'
            }
        }
        stage('Lint') {
            steps {
                sh 'echo "Check linting"'
                sh 'make lint'
            }
        }
        stage('Push') {
            steps {
                sh 'echo "Pushing docker image"'
                sh 'sh push_docker.sh'
            }
        }
    }
}
