pipeline {
    agent any
    stages {
        stage('first') {
            steps {
                dir("app") {
                    sh "pwd"
                }
            }
        }
        stage('Build') {
            steps {
                dir("app") {
                    sh '''
                        pwd
                        ls
                        echo "Building docker image"'
                        sh 'make build'
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                dir("app") {
                    sh 'echo "Testing image"'
                    sh 'make test'
                }
            }
        }
        stage('Lint') {
            steps {
                dir("app") {
                    sh 'echo "Check linting"'
                    sh 'make lint'
                }
            }
        }
        stage('Push') {
            steps {
                dir("app") {
                    sh 'echo "Pushing docker image"'
                    sh 'sh push_docker.sh'
                }
            }
        }
    }
}
