pipeline {
    agent any
    environment 
    {
        VERSION = 'latest'
        PROJECT = '318180760014.dkr.ecr.us-west-2.amazonaws.com/udacity-project'
        IMAGE = 'fibonacci:latest'
        ECRURL = 'https://318180760014.dkr.ecr.us-west-2.amazonaws.com'
        ECRCRED = 'ecr_credentials'
    }
    stages {
        stage('Build preparations') {
            steps {
                script {
                    gitCommitHash = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
                    shortCommitHash = gitCommitHash.take(7)
                    VERSION = shortCommitHash
                    currentBuild.displayName = "#${BUILD_ID}-${VERSION}"
                    IMAGE = "$PROJECT:$VERSION"
                }
            }
        }
        stage('Build') {
            steps {
                script {
                    dir("app") {
                        sh '''
                            pwd
                            echo "Building docker image"
                        '''
                        docker.build("$IMAGE")
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir("app") {
                        sh '''
                            echo "Testing image"
                            docker run --entrypoint=python3 $IMAGE -m unittest discover -s tests -p *Test*.py -v
                        '''
                    }
                }
            }
        }
        stage('Lint') {
            steps {
                script {
                    dir("app") {
                        sh '''
                            echo "Check linting"
                            make lint
                        '''
                    }
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    dir("app") {
                        sh '''
                            echo "Pushing docker image"
                        '''
                        docker.withRegistry("https://your.ecr.domain.amazonws.com", "ecr:us-east-1:credential-id") {
                            docker.image("your-image-name").push()
                        }
                    }
                }
            }
        }
    }
}
