apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibonacci
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: fibonacci
        version: 1.0.0
    spec:
      containers:
        - name: fibonacci
          image: 318180760014.dkr.ecr.us-west-2.amazonaws.com/udacity-project:latest
          ports:
            - name: http
              containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 2
      imagePullSecrets:
      - name: us-west-2-ecr-registry 